modLoader="javafml"
loaderVersion="[34,)"
license="MIT"
issueTrackerURL="https://github.com/janLindner/ultimate-lights/issues"

[[mods]]
modId="ultimatelights"
version="${file.jarVersion}"
displayName="Lights Mod"
logoFile="ultimatelights.png"
authors="HSGMiner"
description='''
'''
